# Generated by Django 5.0.6 on 2024-05-17 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
